# Generated by Django 4.2.3 on 2023-08-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_paciente_ci'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='CI',
        ),
    ]
