# Generated by Django 4.2.3 on 2023-08-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_remove_paciente_ci'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='paciente',
        ),
        migrations.AddField(
            model_name='cita',
            name='anio',
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name='cita',
            name='descripcion',
            field=models.TextField(default='Describa cual es su padecimiento'),
        ),
        migrations.AddField(
            model_name='cita',
            name='dia',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cita',
            name='mes',
            field=models.IntegerField(default=1),
        ),
    ]
