# Generated by Django 4.2.3 on 2023-08-15 17:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_remove_cita_duracion_remove_cita_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='mes',
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cita',
            name='hora',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.paciente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
