# Generated by Django 4.2.3 on 2023-08-15 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_remove_cita_anio_remove_cita_dia_remove_cita_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.paciente'),
        ),
    ]
