# Generated by Django 4.2.3 on 2023-08-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_alter_cita_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='paciente',
        ),
        migrations.AddField(
            model_name='cita',
            name='año',
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name='cita',
            name='dia',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cita',
            name='mes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cita',
            name='descripcion',
            field=models.TextField(default='Describa cual es su padecimiento'),
        ),
    ]
